#!/usr/bin/env python
# coding: utf-8

# - Combine visits and cart using a left merge.
# - How long is your merged DataFrame?
# - How many of the timestamps are null for the column cart_time?
# - What percent of users who visited site ended up not placing a t-shirt in their cart?
# - Repeat the left merge for cart and checkout and count null values. What percentage of users put items in their cart, but did not proceed to checkout?

# In[1]:


import pandas as pd
import numpy as np


# In[5]:


purchase=pd.read_csv(r"C:\Users\HP\Downloads\purchase.csv")
visits=pd.read_csv(r"C:\Users\HP\Downloads\visits.csv")
cart=pd.read_csv(r"C:\Users\HP\Downloads\cart.csv")
check_out=pd.read_csv(r"C:\Users\HP\Downloads\checkout.csv")


# In[6]:


visits


# In[15]:


cart


# In[27]:


df=pd.merge(visits,cart,how='left')


# In[19]:


df.shape


# In[28]:


df.cart_time.isna().value_counts()


# In[29]:


df1=pd.merge(visits,cart,how="outer")


# In[30]:


df1


# In[38]:


df1.cart_time.isna().value_counts()


# In[46]:


v=visits.user_id.count()
v


# In[47]:


per=(1652/v)*100
print("percentage:",per)


# In[48]:


df2=pd.merge(cart,check_out,how="left")
df2


# In[55]:


df2.isna().value_counts()


# In[56]:


b=cart.user_id.count()
b


# In[58]:


per=(122/b)*100
print("percentage:",per)


# In[ ]:




